import { useParams, useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import { ArrowLeft, ArrowRight, Bot, Brain, Target, BarChart3, Zap, MessageCircle, CheckCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import Navbar from "@/components/Navbar";

const featureData: Record<string, {
  icon: typeof Bot;
  title: string;
  tagline: string;
  description: string;
  benefits: string[];
  howItWorks: { step: string; detail: string }[];
  cta: { label: string; path: string };
}> = {
  "ai-chatbot": {
    icon: Bot,
    title: "AI Chatbot Mentor",
    tagline: "Your 24/7 Defence Exam Guide",
    description: "OliveBot is an intelligent AI mentor trained specifically on defence exam patterns, syllabi, and strategies. Ask any doubt — from solving maths problems to understanding geopolitics — and get instant, accurate explanations tailored to NDA, CDS, AFCAT, and SSB preparation.",
    benefits: [
      "Instant answers to any defence exam doubt",
      "Trained on NDA, CDS, AFCAT & SSB syllabi",
      "Explains concepts step-by-step with examples",
      "Available 24/7 — study at your own pace",
      "Remembers your conversation context for follow-ups",
      "Suggests practice questions based on your doubts",
    ],
    howItWorks: [
      { step: "Click the chat widget", detail: "The OliveBot icon appears on every page. Click it to open the chat panel." },
      { step: "Ask your question", detail: "Type any doubt — maths problem, GK question, SSB strategy, or exam guidance." },
      { step: "Get AI-powered response", detail: "OliveBot responds with detailed, exam-relevant explanations in real-time." },
      { step: "Continue the conversation", detail: "Ask follow-ups, request practice questions, or switch topics seamlessly." },
    ],
    cta: { label: "Try OliveBot Now", path: "/dashboard" },
  },
  "study-planner": {
    icon: Brain,
    title: "Agentic AI Study Planner",
    tagline: "Your Personalized Study Schedule",
    description: "Our AI agent creates a comprehensive, adaptive study plan based on your target exam, available time, strengths, and weaknesses. It breaks down your entire syllabus into daily tasks and adjusts as you progress.",
    benefits: [
      "Personalized daily study schedule based on your exam date",
      "Adapts to your strengths and weak areas automatically",
      "Covers entire syllabus with prioritized topics",
      "Includes revision cycles and mock test days",
      "Tracks completion and adjusts remaining plan",
      "Supports NDA, CDS, AFCAT, SSB & CAPF exams",
    ],
    howItWorks: [
      { step: "Select your target exam", detail: "Choose from NDA, CDS, AFCAT, INET, CAPF, or SSB Interview." },
      { step: "Set your exam date", detail: "Enter your exam date so the AI can calculate the optimal preparation timeline." },
      { step: "AI generates your plan", detail: "The AI agent creates a day-by-day study plan covering all subjects and topics." },
      { step: "Follow & track progress", detail: "Check off completed tasks and the plan adjusts to keep you on track." },
    ],
    cta: { label: "Generate My Study Plan", path: "/study-planner" },
  },
  "mock-tests": {
    icon: Target,
    title: "Smart Mock Tests",
    tagline: "AI-Generated Tests That Challenge You",
    description: "Every mock test is uniquely generated by AI to match real exam patterns. Tests adapt to your performance — if you're scoring well, difficulty increases. If you're struggling, the AI focuses on your weak areas to build confidence.",
    benefits: [
      "Unlimited AI-generated mock tests for every exam",
      "Matches real exam pattern, timing, and difficulty",
      "Adaptive difficulty based on your performance",
      "Instant scoring with detailed explanations",
      "Topic-wise and full-length test options",
      "Negative marking simulation for realistic practice",
    ],
    howItWorks: [
      { step: "Choose exam & subject", detail: "Select your target exam and optionally pick specific subjects to focus on." },
      { step: "AI generates the test", detail: "The AI creates a fresh set of MCQs matching the real exam pattern." },
      { step: "Take the timed test", detail: "Attempt questions within the time limit, just like the actual exam." },
      { step: "Review results & analytics", detail: "Get instant scoring, correct answers, explanations, and performance insights." },
    ],
    cta: { label: "Take a Mock Test", path: "/mock-test" },
  },
  "performance-analytics": {
    icon: BarChart3,
    title: "Performance Analytics",
    tagline: "Data-Driven Improvement",
    description: "Deep AI-driven analysis of all your test results. Track your progress over time, identify weak topics with precision, compare with peer benchmarks, and get actionable strategies to improve your scores consistently.",
    benefits: [
      "Visual score trends and accuracy graphs",
      "Subject-wise and topic-wise breakdown",
      "Identify your weakest areas with precision",
      "Track improvement over days, weeks, and months",
      "AI-generated improvement recommendations",
      "Compare your performance with peer benchmarks",
    ],
    howItWorks: [
      { step: "Take mock tests regularly", detail: "The more tests you take, the richer your analytics become." },
      { step: "View your dashboard", detail: "Access comprehensive charts and graphs showing your performance trends." },
      { step: "Identify weak areas", detail: "The AI highlights subjects and topics where you need more practice." },
      { step: "Follow AI recommendations", detail: "Get personalized strategies to improve your weakest areas." },
    ],
    cta: { label: "View My Analytics", path: "/analysis" },
  },
  "answer-evaluation": {
    icon: Zap,
    title: "Instant Answer Evaluation",
    tagline: "AI-Powered Scoring & Feedback",
    description: "Write descriptive answers for SSB or CAPF exams and get instant AI-powered evaluation. The AI scores your response, provides detailed feedback on content, structure, and language, and suggests model answers for comparison.",
    benefits: [
      "Instant scoring for descriptive answers",
      "Detailed feedback on content accuracy and relevance",
      "Language, grammar, and structure analysis",
      "Model answers for comparison and learning",
      "Supports essay, precis, and comprehension answers",
      "Practice with unlimited prompts and topics",
    ],
    howItWorks: [
      { step: "Choose a topic or get a random one", detail: "Pick from a curated list or let the AI generate a fresh topic." },
      { step: "Write your answer", detail: "Type your essay, precis, or descriptive answer in the editor." },
      { step: "AI evaluates instantly", detail: "Get a score out of 10 with feedback on content, structure, and language." },
      { step: "Compare with model answer", detail: "Review the AI-generated model answer to understand the ideal response." },
    ],
    cta: { label: "Try Answer Evaluation", path: "/dashboard" },
  },
  "interview-simulator": {
    icon: MessageCircle,
    title: "AI Interview Simulator",
    tagline: "Practice SSB Interviews with AI",
    description: "Prepare for SSB Personal Interviews with our AI simulator. The AI asks questions based on your PIQ (Personal Information Questionnaire), evaluates your responses in real-time, and provides feedback on confidence, clarity, and content.",
    benefits: [
      "PIQ-based question generation",
      "Real-time response evaluation",
      "Feedback on confidence, clarity, and content",
      "Practice rapid-fire and situational questions",
      "Tips for body language and communication",
      "Unlimited practice sessions",
    ],
    howItWorks: [
      { step: "Fill your PIQ details", detail: "Enter your hobbies, achievements, background — just like the real PIQ form." },
      { step: "Start the AI interview", detail: "The AI asks questions based on your PIQ and defence knowledge." },
      { step: "Respond naturally", detail: "Type your answers as you would speak them in a real interview." },
      { step: "Get detailed feedback", detail: "Receive scoring and tips on how to improve your responses." },
    ],
    cta: { label: "Start Interview Practice", path: "/dashboard" },
  },
};

const AIFeatureDetail = () => {
  const { featureSlug } = useParams<{ featureSlug: string }>();
  const navigate = useNavigate();
  const feature = featureSlug ? featureData[featureSlug] : null;

  if (!feature) {
    return (
      <div className="min-h-screen bg-background">
        <Navbar />
        <main className="container mx-auto px-4 pt-24 pb-12 text-center">
          <h1 className="font-display text-3xl font-bold text-foreground mb-4">Feature Not Found</h1>
          <Button onClick={() => navigate("/")} className="bg-gold text-accent-foreground hover:bg-gold-light">Go Home</Button>
        </main>
      </div>
    );
  }

  const Icon = feature.icon;

  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <main className="pt-24 pb-16">
        {/* Hero */}
        <section className="bg-muted/50 py-16">
          <div className="container mx-auto px-4">
            <Button variant="ghost" onClick={() => navigate("/#ai-features")} className="text-muted-foreground hover:text-gold hover:bg-gold/10 mb-6">
              <ArrowLeft className="mr-2 h-4 w-4" /> Back to AI Features
            </Button>
            <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="flex items-start gap-6">
              <div className="p-4 rounded-2xl bg-gold/10 shrink-0 hidden sm:block">
                <Icon className="h-10 w-10 text-gold" />
              </div>
              <div>
                <span className="text-sm font-semibold tracking-widest text-gold uppercase">AI Feature</span>
                <h1 className="font-display text-3xl md:text-5xl font-bold text-foreground mt-2 mb-3">{feature.title}</h1>
                <p className="text-muted-foreground text-lg font-body max-w-2xl">{feature.description}</p>
                <Button onClick={() => navigate(feature.cta.path)} className="bg-gold text-accent-foreground hover:bg-gold-light font-semibold shadow-gold mt-6">
                  {feature.cta.label} <ArrowRight className="ml-2 h-4 w-4" />
                </Button>
              </div>
            </motion.div>
          </div>
        </section>

        <div className="container mx-auto px-4 py-12 space-y-16">
          {/* Benefits */}
          <motion.section initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}>
            <h2 className="font-display text-2xl font-bold text-foreground mb-6">Key Benefits</h2>
            <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
              {feature.benefits.map((benefit, i) => (
                <div key={i} className="flex items-start gap-3 bg-card rounded-lg border border-border p-4">
                  <CheckCircle className="h-5 w-5 text-gold shrink-0 mt-0.5" />
                  <p className="text-sm text-muted-foreground font-body">{benefit}</p>
                </div>
              ))}
            </div>
          </motion.section>

          {/* How It Works */}
          <motion.section initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }}>
            <h2 className="font-display text-2xl font-bold text-foreground mb-6">How It Works</h2>
            <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
              {feature.howItWorks.map((step, i) => (
                <div key={i} className="relative bg-card rounded-xl border border-border p-6">
                  <div className="w-8 h-8 rounded-full bg-gold text-accent-foreground flex items-center justify-center text-sm font-bold mb-4">{i + 1}</div>
                  <h3 className="font-display text-base font-semibold text-foreground mb-2">{step.step}</h3>
                  <p className="text-sm text-muted-foreground font-body">{step.detail}</p>
                </div>
              ))}
            </div>
          </motion.section>

          {/* CTA */}
          <motion.div initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} className="text-center bg-primary rounded-2xl p-10">
            <h2 className="font-display text-2xl md:text-3xl font-bold text-primary-foreground mb-4">
              Start using {feature.title}
            </h2>
            <p className="text-primary-foreground/60 mb-8 font-body">{feature.tagline}</p>
            <Button onClick={() => navigate(feature.cta.path)} className="bg-gold text-accent-foreground hover:bg-gold-light font-semibold shadow-gold">
              {feature.cta.label} <ArrowRight className="ml-2 h-4 w-4" />
            </Button>
          </motion.div>
        </div>
      </main>
    </div>
  );
};

export default AIFeatureDetail;
